version: '3.8'
services:
  backend: 
    image: backend
    build: backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
 
  frontend:
    image: frontend
    build: 
      context: frontend
      args:
        - BACKEND_URL=http://localhost:8080
    ports:
      - "5001:5000"

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379