FROM node:16-alpine3.17 as builder

ARG BACKEND_URL="http://localhost:8080"

WORKDIR /app

COPY package-lock.json ./ \
  package.json ./

RUN npm ci

COPY . .

RUN REACT_APP_BACKEND_URL=$BACKEND_URL npm run build

FROM nginx:1.25.1-alpine-slim

WORKDIR /app

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 5000:80

RUN adduser appuser -D
USER appuser

CMD ["nginx", "-g", "daemon off;"]