FROM golang:1.16-alpine AS builder

WORKDIR /app

COPY ./go.mod ./
RUN go mod download

COPY . .

RUN go get ./ && \
  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /main

FROM scratch

COPY --from=builder /main /main

ENTRYPOINT ["/main"]