version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./example-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80

  backend: 
    image: backend
    build: example-backend
    expose:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - database
 
  frontend:
    image: frontend
    build: 
      context: example-frontend
      args:
        - BACKEND_URL=http://localhost:8080
    expose:
      - 5000

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379

  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - ./database:/var/lib/postgresql/data
