version: '3.8'
services:
  backend: 
    image: backend
    build: example-backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - database
 
  frontend:
    image: frontend
    build: 
      context: example-frontend
      args:
        - BACKEND_URL=http://localhost:8080
    ports:
      - "5001:5000"

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379

  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
