FROM node:20-alpine3.17 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package-lock.json package.json ./

RUN npm ci

COPY . .

RUN astro build

FROM nginx:latest

EXPOSE 3000

RUN sed -i "s/80/3000/g" /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]