version: '3.8'
services:
  backend: 
    image: backend
    build: backend
    ports:
      - "8080:8080"
    environment:
      - REQUEST_ORIGIN=http://localhost:5001
 
  frontend:
    image: frontend
    build: 
      context: frontend
      args:
        - BACKEND_URL=http://localhost:8080
    ports:
      - "5001:5000"